/** @typedef {{ id: string, name: string, tagline: string, accent: string, accentRgb: string, icon: string, category: string, defaults: { cropPreset: string, leftPercent: number, marginPercent: number, includeInvoiceText: boolean, skipBlank: boolean, smartScan: boolean }, uploadHint: string, layoutNote: string }} Platform */

/** @type {Record<string, Platform>} */
export const PLATFORMS = {
  amazon: {
    id: "amazon",
    name: "Amazon",
    tagline: "Seller shipping PDFs — 2 labels + invoices per page",
    accent: "#ff9900",
    accentRgb: "255, 153, 0",
    icon: "A",
    category: "marketplace",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 50,
      labelHeightPercent: 50,
      marginPercent: 0.5,
      includeInvoiceText: true,
      skipBlank: true,
      smartScan: true,
    },
    uploadHint: "Upload the official Amazon multi-label shipping PDF.",
    layoutNote: "Shipping label on the left (50%), tax invoice on the right — 2 labels per A4 page.",
  },
  flipkart: {
    id: "flipkart",
    name: "Flipkart",
    tagline: "Ekart / Flipkart shipping label sheets",
    accent: "#2874f0",
    accentRgb: "40, 116, 240",
    icon: "F",
    category: "marketplace",
    defaults: {
      cropPreset: "top-split",
      leftPercent: 100,
      labelHeightPercent: 50,
      marginPercent: 0.5,
      includeInvoiceText: false,
      skipBlank: true,
      smartScan: true,
    },
    uploadHint: "Upload Flipkart seller panel shipping PDF export.",
    layoutNote: "Shipping label on top (50%), tax invoice on the bottom — invoice removed automatically.",
  },
  meesho: {
    id: "meesho",
    name: "Meesho",
    tagline: "Supplier shipping labels from Meesho panel",
    accent: "#9f2089",
    accentRgb: "159, 32, 137",
    icon: "M",
    category: "marketplace",
    defaults: {
      cropPreset: "top-split",
      leftPercent: 100,
      labelHeightPercent: 58,
      marginPercent: 0.5,
      includeInvoiceText: false,
      skipBlank: true,
      smartScan: true,
    },
    uploadHint: "Upload Meesho bulk shipping label PDF.",
    layoutNote: "Shipping label on top (58%), tax invoice on the bottom — invoice removed automatically.",
  },
  myntra: {
    id: "myntra",
    name: "Myntra",
    tagline: "Partner portal shipping documents",
    accent: "#ff3f6c",
    accentRgb: "255, 63, 108",
    icon: "My",
    category: "marketplace",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 50,
      marginPercent: 1,
      includeInvoiceText: true,
      skipBlank: true,
    },
    uploadHint: "Upload Myntra shipping label PDF from seller tools.",
    layoutNote: "Standard 2-up layout with label + packing slip columns.",
  },
  nykaa: {
    id: "nykaa",
    name: "Nykaa",
    tagline: "Beauty & fashion marketplace labels",
    accent: "#fc2779",
    accentRgb: "252, 39, 121",
    icon: "N",
    category: "marketplace",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 50,
      marginPercent: 1,
      includeInvoiceText: true,
      skipBlank: true,
    },
    uploadHint: "Upload Nykaa seller shipping PDF.",
    layoutNote: "Use left-half preset; tweak margin if barcode is cut off.",
  },
  ajio: {
    id: "ajio",
    name: "AJIO",
    tagline: "Reliance AJIO seller shipping PDFs",
    accent: "#2e2e2e",
    accentRgb: "46, 46, 46",
    icon: "Aj",
    category: "marketplace",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 49,
      marginPercent: 1,
      includeInvoiceText: true,
      skipBlank: true,
    },
    uploadHint: "Upload AJIO shipping label export PDF.",
    layoutNote: "Labels typically on the left column of a 2-column page.",
  },
  snapdeal: {
    id: "snapdeal",
    name: "Snapdeal",
    tagline: "Snapdeal seller shipping sheets",
    accent: "#e40046",
    accentRgb: "228, 0, 70",
    icon: "S",
    category: "marketplace",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 50,
      marginPercent: 1,
      includeInvoiceText: true,
      skipBlank: true,
    },
    uploadHint: "Upload Snapdeal shipping PDF from order bulk print.",
    layoutNote: "Match source layout if your export flips columns.",
  },
  shopify: {
    id: "shopify",
    name: "Shopify",
    tagline: "Shopify Shipping / third-party label PDFs",
    accent: "#95bf47",
    accentRgb: "149, 191, 71",
    icon: "Sh",
    category: "dtc",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 50,
      marginPercent: 0.5,
      includeInvoiceText: false,
      skipBlank: false,
      smartScan: false,
    },
    uploadHint: "Upload Shopify or app-generated multi-label PDF.",
    layoutNote: "DTC PDFs vary — try top-half or source size if needed.",
  },
  shiprocket: {
    id: "shiprocket",
    name: "Shiprocket",
    tagline: "Aggregated courier label bulk PDFs",
    accent: "#6f57e9",
    accentRgb: "111, 87, 233",
    icon: "SR",
    category: "logistics",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 50,
      marginPercent: 0.5,
      includeInvoiceText: false,
      skipBlank: true,
    },
    uploadHint: "Upload Shiprocket bulk label PDF.",
    layoutNote: "Often 2 labels per A4 — use left-half or top-half preset.",
  },
  delhivery: {
    id: "delhivery",
    name: "Delhivery",
    tagline: "Delhivery client panel label PDFs",
    accent: "#ed1c24",
    accentRgb: "237, 28, 36",
    icon: "D",
    category: "logistics",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 50,
      marginPercent: 0.5,
      includeInvoiceText: false,
      skipBlank: true,
    },
    uploadHint: "Upload Delhivery bulk shipping label PDF.",
    layoutNote: "Single or dual labels per page depending on export.",
  },
  blinkit: {
    id: "blinkit",
    name: "Blinkit",
    tagline: "Quick-commerce partner shipping labels",
    accent: "#f8cb46",
    accentRgb: "248, 203, 70",
    icon: "B",
    category: "quickcommerce",
    defaults: {
      cropPreset: "top-half",
      leftPercent: 50,
      marginPercent: 0.5,
      includeInvoiceText: false,
      skipBlank: true,
    },
    uploadHint: "Upload Blinkit / Zomato Hyperpure style label PDF.",
    layoutNote: "Some templates use top/bottom rows instead of columns.",
  },
  zepto: {
    id: "zepto",
    name: "Zepto",
    tagline: "Zepto seller & warehouse label PDFs",
    accent: "#9500ff",
    accentRgb: "149, 0, 255",
    icon: "Z",
    category: "quickcommerce",
    defaults: {
      cropPreset: "top-half",
      leftPercent: 50,
      marginPercent: 0.5,
      includeInvoiceText: false,
      skipBlank: true,
    },
    uploadHint: "Upload Zepto shipping label PDF export.",
    layoutNote: "Try top-half if labels stack vertically on the page.",
  },
  glowroad: {
    id: "glowroad",
    name: "Glowroad",
    tagline: "Reseller network shipping PDFs",
    accent: "#00a86b",
    accentRgb: "0, 168, 107",
    icon: "G",
    category: "marketplace",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 51,
      marginPercent: 1,
      includeInvoiceText: true,
      skipBlank: true,
    },
    uploadHint: "Upload Glowroad bulk label PDF.",
    layoutNote: "Similar 2-up layout to other Indian marketplaces.",
  },
  indiamart: {
    id: "indiamart",
    name: "IndiaMART",
    tagline: "B2B dispatch & courier label sheets",
    accent: "#2e3192",
    accentRgb: "46, 49, 146",
    icon: "IM",
    category: "b2b",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 50,
      marginPercent: 1,
      includeInvoiceText: true,
      skipBlank: false,
      smartScan: false,
    },
    uploadHint: "Upload IndiaMART or logistics partner label PDF.",
    layoutNote: "B2B formats differ — adjust layout preset as needed.",
  },
  generic: {
    id: "generic",
    name: "Universal",
    tagline: "Any 2-label-per-page PDF — full manual control",
    accent: "#14b8a6",
    accentRgb: "20, 184, 166",
    icon: "∞",
    category: "utility",
    defaults: {
      cropPreset: "left-half",
      leftPercent: 50,
      marginPercent: 1,
      includeInvoiceText: true,
      skipBlank: true,
    },
    uploadHint: "Upload any marketplace or courier multi-label PDF.",
    layoutNote: "Pick the source layout that matches your file.",
  },
};

export const PLATFORM_LIST = Object.values(PLATFORMS);

export const CATEGORY_LABELS = {
  marketplace: "Marketplaces",
  dtc: "Direct-to-consumer",
  logistics: "Logistics & 3PL",
  quickcommerce: "Quick commerce",
  b2b: "B2B",
  utility: "Utilities",
};

/** Roadmap tools — shown on hub, not yet implemented */
export const SUGGESTED_TOOLS = [
  {
    id: "pick-list",
    name: "Pick List Generator",
    description: "Turn order CSV into warehouse pick lists sorted by bin or SKU.",
    category: "fulfillment",
    status: "planned",
  },
  {
    id: "pack-slip",
    name: "Pack Slip Merger",
    description: "Merge packing slips with labels for single-print workflows.",
    category: "fulfillment",
    status: "planned",
  },
  {
    id: "barcode-bulk",
    name: "Bulk Barcode PDF",
    description: "Generate SKU / FNSKU barcode sheets from spreadsheet upload.",
    category: "catalog",
    status: "planned",
  },
  {
    id: "return-labels",
    name: "Return Label Organizer",
    description: "Split and sort return labels by order ID for RTO processing.",
    category: "fulfillment",
    status: "planned",
  },
  {
    id: "gst-invoice",
    name: "GST Invoice Formatter",
    description: "Normalize marketplace tax invoices to your letterhead layout.",
    category: "finance",
    status: "planned",
  },
  {
    id: "dim-weight",
    name: "Volumetric Weight Calculator",
    description: "Compare courier chargeable weight across box sizes before dispatch.",
    category: "shipping",
    status: "planned",
  },
  {
    id: "hsn-lookup",
    name: "HSN Code Assistant",
    description: "Suggest HSN codes from product titles for GST filing prep.",
    category: "finance",
    status: "planned",
  },
  {
    id: "manifest",
    name: "Dispatch Manifest",
    description: "Build daily handover manifests from scanned AWB lists.",
    category: "shipping",
    status: "planned",
  },
  {
    id: "sku-label",
    name: "Warehouse Bin Labels",
    description: "Print shelf and bin labels for FBA / own-warehouse storage.",
    category: "catalog",
    status: "planned",
  },
  {
    id: "order-csv",
    name: "CSV → Label Matcher",
    description: "Verify every order in a CSV has a matching label in your PDF.",
    category: "fulfillment",
    status: "planned",
  },
];

export function getPlatform(id) {
  return PLATFORMS[id] || PLATFORMS.generic;
}
